import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, AppState, Pressable, RefreshControl, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth, request } from './api';
import { Chart } from './Charts';
import { analyzeTelemetry } from '../shared/statistics';
import { demoReadings } from '../shared/demo';
const n = value => value == null || !Number.isFinite(value) ? '—' : value.toLocaleString('pt-BR', { maximumFractionDigits: 2 });
function Button({ children, onPress, disabled, secondary }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, disabled && { opacity: .5 }]}><Text style={[s.buttonText, secondary && { color: '#24675b' }]}>{children}</Text></Pressable>; }
function Card({ title, children }) { return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>; }
export default function App() {
  const [user, setUser] = useState(null), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [register, setRegister] = useState(false);
  const [demo, setDemo] = useState(false), [device, setDevice] = useState(null), [rows, setRows] = useState([]), [hours, setHours] = useState(24), [revision, setRevision] = useState(0);
  const [busy, setBusy] = useState(false), [refreshing, setRefreshing] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState(''), [blynk, setBlynk] = useState(false), [truncated, setTruncated] = useState(false), [code, setCode] = useState('');
  const [appState, setAppState] = useState(AppState.currentState);
  const stats = useMemo(() => analyzeTelemetry(rows), [rows]);
  useEffect(() => onAuthStateChanged(auth, setUser), []);
  useEffect(() => { const sub = AppState.addEventListener('change', setAppState); return () => sub.remove(); }, []);
  useEffect(() => {
    const controller = new AbortController(); let timer;
    setDevice(null); setRows([]); setTruncated(false); setError(''); setMessage('');
    if (demo) { const readings = demoReadings(); setRows(readings); setDevice({ id: 'demo', name: 'Demonstração', latest: readings.at(-1) }); setRefreshing(false); }
    else if (user && appState === 'active') {
      const poll = async () => {
        try {
          const [list, config] = await Promise.all([request('/api/v1/devices', { signal: controller.signal }), request('/api/v1/status', { signal: controller.signal })]);
          const d = list.devices[0]; let data = { readings: [], hasMore: false };
          if (d) { const to = new Date(), from = new Date(to.getTime() - hours * 3600000); data = await request(`/api/v1/devices/${d.id}/telemetry?from=${from.toISOString()}&to=${to.toISOString()}&limit=1000`, { signal: controller.signal }); }
          if (!controller.signal.aborted) { setDevice(d || null); setRows(data.readings); setBlynk(config.blynk); setTruncated(data.hasMore); setError(''); }
        } catch (e) { if (!controller.signal.aborted) setError(e.message + ' Dados exibidos podem estar desatualizados.'); }
        finally { if (!controller.signal.aborted) { setRefreshing(false); timer = setTimeout(poll, 10000); } }
      }; void poll();
    } else setRefreshing(false);
    return () => { controller.abort(); clearTimeout(timer); };
  }, [user, demo, hours, revision, appState]);
  async function action(fn) { setBusy(true); setError(''); setMessage(''); try { await fn(); } catch (e) { setError(e.message?.includes('Firebase') ? 'Não foi possível entrar. Confira e-mail e senha (mínimo 6 caracteres).' : e.message); } finally { setBusy(false); } }
  const latest = device?.latest;
  return <SafeAreaProvider><SafeAreaView style={s.safe}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); setRevision(v => v + 1); }}/> }>
    <View style={s.header}><Text style={s.brand}>invista<Text style={{ color: '#248273' }}>+</Text></Text>{user && <Button secondary onPress={() => signOut(auth)}>Sair</Button>}</View>
    <Text style={s.eyebrow}>TERMINAL FINANCEIRO · IOT</Text><Text style={s.heading}>Seu terminal, onde você estiver.</Text><Text style={s.description}>Leituras, estatísticas e controle em uma só tela.</Text>
    <View style={s.row}><Button secondary={demo} onPress={() => setDemo(false)}>Meu dispositivo</Button><Button secondary={!demo} onPress={() => setDemo(true)}>Demonstração</Button></View>
    {demo && <Text style={s.notice}>Amostras ilustrativas. Controles desativados. Nada é salvo no banco.</Text>}{error !== '' && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}{message !== '' && <Text accessibilityLiveRegion="polite" style={s.notice}>{message}</Text>}
    {!demo && !user && <Card title={register ? 'Criar conta' : 'Entrar no Invista+'}><Text style={s.description}>Use a mesma conta da versão Web.</Text><TextInput accessibilityLabel="E-mail" placeholder="E-mail" keyboardType="email-address" autoCapitalize="none" autoComplete="email" value={email} onChangeText={setEmail} style={s.input}/><TextInput accessibilityLabel="Senha" placeholder="Senha" secureTextEntry autoComplete={register ? 'new-password' : 'current-password'} value={password} onChangeText={setPassword} style={s.input}/><Button disabled={busy} onPress={() => action(async () => { await (register ? createUserWithEmailAndPassword : signInWithEmailAndPassword)(auth, email.trim(), password); setPassword(''); })}>{register ? 'Criar conta' : 'Entrar'}</Button><Button secondary onPress={() => setRegister(!register)}>{register ? 'Já tenho conta' : 'Quero criar uma conta'}</Button></Card>}
    {!demo && user && !device && <Card title="Vincular terminal"><Text style={s.description}>Informe o código privado de vínculo configurado no servidor.</Text><TextInput accessibilityLabel="Código de vínculo" placeholder="Código de vínculo" secureTextEntry autoCapitalize="none" value={code} onChangeText={setCode} style={s.input}/><Button disabled={busy || !code} onPress={() => action(async () => { await request('/api/v1/devices', { method: 'POST', body: { name: 'Meu terminal financeiro', pairingCode: code } }); setCode(''); setRevision(v => v + 1); })}>Vincular</Button></Card>}
    {busy && <ActivityIndicator color="#217c6c"/>}
    {device && <><Text style={s.device}>{device.name} · {demo ? 'ilustrativo' : device.online && !error ? 'recebendo dados' : 'sem leitura recente'}</Text><Text style={s.caption}>Última leitura: {latest ? new Date(latest.receivedAt).toLocaleString('pt-BR') : 'aguardando'}</Text>
      <View style={s.row}>{[1, 24, 168].map(h => <Button key={h} secondary={hours !== h} disabled={demo} onPress={() => setHours(h)}>{h === 1 ? '1 hora' : h === 24 ? '24 horas' : '7 dias'}</Button>)}</View>
      <Card title="Potenciômetro · sensor analógico"><Text style={s.big}>{latest?.riskLevel ?? '—'}<Text style={s.unit}> / 100</Text></Text><View style={s.track}><View style={[s.fill, { width: `${latest?.riskLevel || 0}%` }]}/></View><Text style={s.description}>Perfil: {latest ? latest.riskLevel < 34 ? 'conservador' : latest.riskLevel < 67 ? 'moderado' : 'arrojado' : '—'} · ADC: {latest?.analogRaw ?? '—'}</Text></Card>
      <Card title="Botão · sensor digital"><Text style={s.big}>{stats.totalPresses}<Text style={s.unit}> acionamentos</Text></Text><Text style={s.description}>No período selecionado. Botão {latest?.buttonPressed ? 'pressionado' : 'solto'}.</Text></Card>
      <Card title="LED · atuador"><View style={s.spread}><Text style={s.cardTitle}>{latest ? latest.ledOn ? 'Ligado' : 'Desligado' : 'Sem leitura'}</Text><Switch accessibilityLabel="Ligar LED pelo Blynk" value={Boolean(latest?.ledOn)} disabled={demo || busy || !blynk} onValueChange={on => action(async () => { const r = await request(`/api/v1/devices/${device.id}/actuators/led`, { method: 'PUT', body: { on } }); setMessage(r.message); })} trackColor={{ true: '#258071' }}/></View><Text style={s.caption}>Estado confirmado pela telemetria. {device.latestCommand ? `Último comando: ${device.latestCommand.on ? 'ligar' : 'desligar'}. ` : ''}{!demo && !blynk ? 'Token Blynk ainda não configurado no servidor.' : 'Aguarde a próxima leitura após mudar o interruptor.'}</Text></Card>
      <Card title="Histórico do nível de risco"><Chart rows={rows}/><Text style={s.caption}>Eixo vertical: risco (0–100). Horizontal: horário de recebimento.</Text></Card>
      <Card title="Distribuição dos perfis">{stats.histogram.map(h => <View key={h.profile} style={{ marginBottom: 14 }}><View style={s.spread}><Text style={s.text}>{h.profile}</Text><Text style={s.text}>{h.count}</Text></View><View style={s.track}><View style={[s.fill, { width: `${stats.sampleCount ? h.count / stats.sampleCount * 100 : 0}%` }]}/></View></View>)}</Card>
      <Card title={`Estatísticas · ${stats.sampleCount} amostras`}><Text style={s.caption}>Calculadas no próprio celular sobre os dados recebidos da API. Desvio amostral, Fisher corrigido e excesso de curtose.</Text>{truncated && <Text style={s.notice}>Limite de 1.000 amostras: reduza o período.</Text>}{[['Risco', stats.risk], ['Acionamentos / amostra', stats.presses], ['Acionamentos / minuto', stats.rate]].map(([label, a]) => <View key={label} style={s.statGroup}><Text style={s.cardTitle}>{label}</Text>{[['Média', n(a.mean)], ['Moda', a.modes.length ? a.modes.map(v => n(v)).join(', ') : 'Amodal'], ['Mediana', n(a.median)], ['Desvio padrão', n(a.standardDeviation)], ['Assimetria', n(a.skewness)], ['Excesso de curtose', n(a.excessKurtosis)]].map(([k, v]) => <View style={s.statLine} key={k}><Text style={s.text}>{k}</Text><Text style={s.statValue}>{v}</Text></View>)}</View>)}<Text style={s.caption}>“—”: cálculo indefinido ou amostra insuficiente. Origens: {[...new Set(rows.map(r => r.source))].join(', ') || 'sem dados'}.</Text></Card>
      <Card title="Probabilidades e inferência"><Text style={s.text}>P(risco ≥ 67): {n(stats.probability.highRisk == null ? null : stats.probability.highRisk * 100)}%</Text><Text style={s.text}>P(ao menos 1 acionamento): {n(stats.probability.withPresses == null ? null : stats.probability.withPresses * 100)}%</Text><Text style={s.text}>IC 95% Wilson: {stats.probability.highRiskCI95 ? `${n(stats.probability.highRiskCI95.lower * 100)}% a ${n(stats.probability.highRiskCI95.upper * 100)}%` : '—'}</Text><Text style={s.caption}>{stats.inferenceNote}</Text></Card>
      <Card title="Regressão: risco × acionamentos/min"><Chart rows={rows} scatter regression={stats.regression}/><Text style={s.text}>{stats.regression ? `y = ${n(stats.regression.intercept)} + (${n(stats.regression.slope)})x\nR² = ${n(stats.regression.rSquared)} · r = ${n(stats.regression.r)}` : 'Necessárias 3 amostras e variação nas duas variáveis.'}</Text></Card>
    </>}
    <Text style={s.footer}>Invista+ · Projeto Integrador\nWeb • Mobile • IoT • Estatística</Text>
  </ScrollView></SafeAreaView></SafeAreaProvider>;
}
const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:'#f4f6f0'},content:{padding:20,paddingBottom:45,width:'100%',maxWidth:740,alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:28},brand:{fontSize:30,fontWeight:'800',color:'#173c36',letterSpacing:-1},heading:{fontSize:30,fontWeight:'700',color:'#183d35',marginTop:10,lineHeight:36},eyebrow:{fontSize:10,letterSpacing:2,color:'#5e7e6c',fontWeight:'600'},description:{fontSize:13,color:'#6d8375',lineHeight:21,marginVertical:12},row:{flexDirection:'row',gap:8,flexWrap:'wrap',marginVertical:12},button:{backgroundColor:'#227d6d',borderRadius:9,paddingHorizontal:16,paddingVertical:12,marginVertical:4},buttonText:{color:'#fff',fontWeight:'600',fontSize:13,textAlign:'center'},secondary:{backgroundColor:'#e5eee1'},card:{backgroundColor:'#fff',borderColor:'#dfe8dc',borderWidth:1,borderRadius:15,padding:22,marginTop:16},cardTitle:{fontSize:16,fontWeight:'600',color:'#254e3c',marginBottom:12},input:{backgroundColor:'#f9fbf7',borderColor:'#dce5d6',borderWidth:1,padding:14,borderRadius:8,marginBottom:12,color:'#244434'},big:{fontSize:42,fontWeight:'700',color:'#173d34'},unit:{fontSize:14,fontWeight:'400',color:'#728776'},track:{height:7,borderRadius:7,backgroundColor:'#ecf1e8',overflow:'hidden',marginTop:12},fill:{backgroundColor:'#6ba98b',height:'100%',borderRadius:7},spread:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:16},text:{color:'#4f6f5c',fontSize:13,lineHeight:24},caption:{fontSize:11,lineHeight:18,color:'#7c8e7c',marginTop:8},notice:{fontSize:12,lineHeight:19,color:'#8a672f',padding:15,backgroundColor:'#fff3d9',borderRadius:8,marginVertical:12},error:{fontSize:12,lineHeight:19,color:'#9c4e3e',padding:15,backgroundColor:'#ffece4',borderRadius:8,marginVertical:12},device:{fontSize:14,color:'#3b6651',fontWeight:'600',marginTop:20},statGroup:{borderTopWidth:1,borderTopColor:'#e8eee2',marginTop:20,paddingTop:20},statLine:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:5},statValue:{fontSize:13,color:'#30563f',fontWeight:'600',flexShrink:1,textAlign:'right'},footer:{textAlign:'center',fontSize:11,lineHeight:19,color:'#879883',marginTop:35}
});
