import { mkdirSync, writeFileSync } from 'node:fs';
const ref = name => ({ $ref: `#/components/schemas/${name}` });
const object = (properties, required = Object.keys(properties)) => ({ type: 'object', properties, required });
const str = { type: 'string' }, bool = { type: 'boolean' }, integer = { type: 'integer' }, num = { type: 'number', nullable: true }, date = { type: 'string', format: 'date-time' };
const response = (schema, description = 'Sucesso') => ({ description, content: { 'application/json': { schema } } });
const body = schema => ({ required: true, content: { 'application/json': { schema } } });
const errors = Object.fromEntries([400,401,403,404,409,413,429,502,503,504].map(code => [code, response(ref('Error'), ({400:'Entrada inválida',401:'Não autenticado',403:'Código incorreto',404:'Não encontrado',409:'Conflito de vínculo ou leitura',413:'Corpo acima de 48 KB',429:'Limite de uso',502:'Falha do serviço externo',503:'Serviço não configurado/indisponível',504:'Tempo esgotado'})[code])]));
const auth = [{ Firebase: [] }], id = { name: 'id', in: 'path', required: true, schema: str, example: 'terminal-01' };
const windowParams = [{ name:'from',in:'query',schema:date,description:'Início inclusivo. Padrão: 24 horas antes de to.' }, { name:'to',in:'query',schema:date,description:'Fim inclusivo. Padrão: agora. Janela máxima de 90 dias.' }, { name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:1000,default:500} }, { name:'before',in:'query',schema:str,description:'Cursor opaco nextCursor retornado na página anterior. Mantenha from e to fixos durante a paginação.' }];
const op = (summary, schema, extra = {}) => ({ summary, responses: {200:response(schema),...errors}, ...extra });
const reading = object({ id:str, sessionId:str, sequence:integer, receivedAt:date, analogRaw:integer, riskLevel:integer, buttonPressed:bool, buttonPresses:integer, intervalSeconds:{type:'number'}, ledOn:bool, source:{type:'string',enum:['wokwi','esp32','simulator']} });
const input = object({ sessionId:{type:'string',pattern:'^[\\w-]{8,64}$'},sequence:{type:'integer',minimum:0,maximum:2147483647},analogRaw:{type:'integer',minimum:0,maximum:4095},buttonPressed:bool,buttonPresses:{type:'integer',minimum:0,maximum:10000},intervalSeconds:{type:'number',minimum:1,maximum:3600},ledOn:bool,source:reading.properties.source });
input.example = {sessionId:'session-example-001',sequence:1,analogRaw:2048,buttonPressed:false,buttonPresses:2,intervalSeconds:10,ledOn:false,source:'wokwi'};
const summary = object({n:integer,mean:num,median:num,modes:{type:'array',items:{type:'number'}},standardDeviation:num,skewness:num,excessKurtosis:num,min:num,max:num});
const stats = object({sampleCount:integer,totalPresses:integer,risk:ref('Descriptive'),presses:ref('Descriptive'),rate:ref('Descriptive'),histogram:{type:'array',items:object({profile:str,count:integer})},probability:object({highRisk:num,withPresses:num,highRiskCI95:{type:'object',nullable:true,properties:{confidence:{type:'number'},lower:num,upper:num,method:str}}}),regression:{type:'object',nullable:true,properties:{n:integer,slope:num,intercept:num,r:num,rSquared:num}},inferenceNote:str,window:ref('Window'),truncated:bool,sources:{type:'array',items:str}});
const paths = {
 '/api/health':{get:op('Disponibilidade da aplicação',object({status:str,version:str,database:bool,mentor:bool}))},
 '/api/perfis':{get:op('Critérios de leitura dos indicadores', {type:'object'})},
 '/api/v1/status':{get:op('Configuração do terminal (sem segredos)',object({database:bool,blynk:bool,deviceId:str,sensors:{type:'array',items:str},actuator:str}))},
 '/api/v1/devices':{
   get:op('Listar terminais da conta',object({devices:{type:'array',items:ref('Device')}}),{security:auth}),
   post:op('Vincular o terminal à conta (idempotente para o mesmo dono)',ref('Device'),{security:auth,requestBody:body(object({name:{type:'string',minLength:1,maxLength:60},pairingCode:str})),responses:{201:response(ref('Device'),'Terminal vinculado; Location contém seu recurso'),...errors}})
 },
 '/api/v1/devices/{id}':{parameters:[id],get:op('Consultar estado confirmado e último comando',ref('Device'),{security:auth}),patch:op('Renomear terminal',ref('Device'),{security:auth,requestBody:body(object({name:{type:'string',minLength:1,maxLength:60}}))})},
 '/api/v1/devices/{id}/telemetry':{parameters:[id],
  post:op('Receber leitura do ESP32',ref('IngestResult'),{security:[{DeviceToken:[]}],description:'Chave de idempotência: sessionId + sequence. Reenvio não duplica contagens; mudar o conteúdo da mesma chave retorna 409. receivedAt é gerado pelo servidor. Exige vínculo prévio à conta.',requestBody:body(ref('TelemetryInput')),responses:{200:response(ref('IngestResult'),'Leitura já registrada'),201:response(ref('IngestResult'),'Leitura criada'),...errors}}),
  get:op('Consultar histórico persistido, do mais recente para o mais antigo',object({readings:{type:'array',items:ref('Reading')},window:ref('Window'),hasMore:bool,nextCursor:{type:'string',nullable:true}}),{security:auth,parameters:windowParams})
 },
 '/api/v1/devices/{id}/statistics':{parameters:[id],get:op('Estatísticas da mesma janela de telemetria',ref('Statistics'),{security:auth,parameters:windowParams,description:'Desvio amostral; Fisher corrigido; excesso de curtose corrigido; probabilidades empíricas; IC de Wilson 95%; regressão OLS de risco × acionamentos/minuto. Null indica cálculo indefinido. Truncated informa limite da amostra.'})},
 '/api/v1/devices/{id}/actuators/led':{parameters:[id],put:op('Enviar estado desejado do LED pelo Blynk V2',ref('Command'),{security:auth,requestBody:body(object({on:bool})),responses:{202:response(ref('Command'),'Aceito pelo Blynk; confira o LED na próxima telemetria. Não confirma execução física.'),...errors}})},
 '/api/v1/favorites':{get:op('Consultar favoritos da conta',ref('Favorites'),{security:auth}),put:op('Substituir favoritos da conta',ref('Favorites'),{security:auth,requestBody:body(ref('Favorites'))})},
 '/api/mentor':{post:op('Conversar com o Mentor Gemini sobre a consulta do scanner',object({texto:str,contexto:{type:'object',nullable:true,additionalProperties:true}}),{security:auth,description:'Até 30 solicitações/dia por conta, intervalo mínimo de 5 s. Snapshot assinado pelo scanner expira em 30 minutos. IA educativa sem acesso a notícias ou cotação em tempo real.',requestBody:body(object({modo:{type:'string',enum:['resumo','pergunta']},pergunta:{type:'string',maxLength:1500},ticker:str,tipo:{type:'string',enum:['acoes','fiis']},perfil:{type:'string',enum:['conservador','moderado','arrojado']},snapshot:ref('Snapshot'),historico:{type:'array',maxItems:8,items:object({role:{type:'string',enum:['user','model']},text:str})}},['modo']))})},
};
for(const tipo of ['acoes','fiis']) paths['/api/'+tipo]={post:op('Analisar '+(tipo==='acoes'?'ação':'FII'),ref('Asset'),{requestBody:body(object({ticker:{type:'string',pattern:'^[A-Za-z]{4}[0-9]{1,2}$',example:tipo==='acoes'?'PETR4':'MXRF11'},perfil:{type:'string',enum:['conservador','moderado','arrojado'],default:'moderado'}},['ticker']))})};
const spec = {openapi:'3.0.3',info:{title:'Invista+ API',version:'3.0.0',description:'Scanner financeiro e terminal IoT: potenciômetro (analógico), botão (digital) e LED. Firestore no servidor; Web React e app Expo. As leituras descrevem interações, não retornos financeiros.'},servers:[{url:'https://invista-chi.vercel.app',description:'Produção'},{url:'http://localhost:3000',description:'Desenvolvimento'}],paths,components:{securitySchemes:{Firebase:{type:'http',scheme:'bearer',bearerFormat:'Firebase ID Token',description:'Token da mesma conta usada na Web e no app.'},DeviceToken:{type:'apiKey',in:'header',name:'X-Device-Token',description:'IOT_DEVICE_TOKEN privado, exclusivo do ESP32.'}},schemas:{Error:object({error:str}),TelemetryInput:input,Reading:reading,Descriptive:summary,Statistics:stats,IngestResult:object({id:str,created:bool,riskLevel:integer,profile:str}),Window:object({from:date,to:date,limit:integer,before:{type:'array',items:str}},['from','to','limit']),Command:object({id:str,on:bool,sentAt:date,transport:{type:'string',enum:['blynk']},status:{type:'string',enum:['sent']},message:str},['id','on','sentAt','transport','status']),Device:object({id:str,name:str,createdAt:date,latest:{...reading,nullable:true},latestCommand:{type:'object',nullable:true,properties:{id:str,on:bool,sentAt:date,transport:str,status:str}},online:bool,profile:{type:'string',nullable:true}}),Favorites:object({tickers:{type:'array',maxItems:30,items:{type:'string',pattern:'^[A-Z]{4}[0-9]{1,2}$'}}}),Snapshot:object({payload:str,signature:str}),Asset:{type:'object',properties:{ticker:str,perfil:str,selicUtilizada:{type:'number'},mentorContext:ref('Snapshot')},additionalProperties:{type:'object',properties:{value:str,class:{type:'string',enum:['neutral','good','bad']},margem:{type:'string',nullable:true}}}}}}};
mkdirSync('docs',{recursive:true});writeFileSync('docs/openapi.json',JSON.stringify(spec,null,2)+'\n');
